export const useFaqItems = () => [
  { title: "faq.depositTitle", body: "faq.depositText" },
  { title: "faq.stakeTitle", body: "faq.stakeText" },
  { title: "faq.profitTitle", body: "faq.profitText" },
  { title: "faq.payoutTitle", body: "faq.payoutText" },
  { title: "faq.withdrawTitle", body: "faq.withdrawText" },
  { title: "faq.minWithdrawTitle", body: "faq.minWithdrawText" },
  { title: "faq.lockedTitle", body: "faq.lockedText" },
  { title: "faq.autoReinvestTitle", body: "faq.autoReinvestText" },
  { title: "faq.emergencyTitle", body: "faq.emergencyText" },
  { title: "faq.tariffsTitle", body: "faq.tariffsText" },
  { title: "faq.upgradeTitle", body: "faq.upgradeText" },
  { title: "faq.referralTitle", body: "faq.referralText" },
  { title: "faq.refBonusTitle", body: "faq.refBonusText" },
  { title: "faq.refClaimTitle", body: "faq.refClaimText" },
  { title: "faq.leaderboardTitle", body: "faq.leaderboardText" },
  { title: "faq.furTitle", body: "faq.furText" },
  { title: "faq.trcTitle", body: "faq.trcText" },
  { title: "faq.supportTitle", body: "faq.supportText" },
];
