-- Add new referral + staking fields
ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "furPending" DECIMAL(65,30) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "furBalance" DECIMAL(65,30) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "totalTurnover" DECIMAL(65,30) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "autoReinvest" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Deposit"
  ADD COLUMN IF NOT EXISTS "autoReinvest" BOOLEAN NOT NULL DEFAULT true;
